services:
  k3s-argo:
    container_name: k3s-argo
    image: "${APP_NAME}:${APP_VERSION}"
    privileged: true
    restart: always
    environment:
      - K3S_KUBECONFIG_MODE=644
    volumes:
      - pv:/var/lib/rancher/k3s/storage
      - /tmp/k3s:/cfg
    networks:
      - k3s-argo
    ports:
      - 6443:6443
      - 2746:2746

networks:
  k3s-argo:

volumes:
  pv:
